
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cards
  description: Cards
  tags:
    - react
    - redux
  links:
    - url: https://example.com/web
      title: Website
      icon: web
spec:
  type: website
  lifecycle: production
  owner: team-a

